-- =====================================================================
-- FIMLM - Registro de Beneficiarios (Jornadas de Apoyo)
-- Esquema de base de datos Oracle
-- =====================================================================

-- ---------------------------------------------------------------------
-- Tabla: beneficiarios
-- Un registro por persona (clave natural: documento_identidad).
-- Reproduce las columnas 14 a 21 de la "Planilla de Registro de
-- Beneficiarios" (FIMLM), mas los datos de la jornada/evento (columnas
-- 3 a 12) en la que fue registrada o actualizada por ultima vez.
-- No se guarda la columna 22 (Firma o huella) por decision del negocio.
-- ---------------------------------------------------------------------
-- NOTA: SQL*Plus (con SQLBLANKLINES en su valor por defecto OFF) corta la
-- ejecucion si encuentra una linea en blanco dentro de un mismo statement.
-- Por eso este CREATE TABLE no tiene lineas en blanco entre columnas.
CREATE TABLE beneficiarios (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Columna 15: Documento de identidad (clave de busqueda/actualizacion)
    documento_identidad     VARCHAR2(20)  NOT NULL,
    -- Columna 14: Nombres y apellidos completos
    nombres_apellidos       VARCHAR2(200) NOT NULL,
    -- Columna 16: Sexo (F/M)
    sexo                    CHAR(1),
    -- Columna 17: Edad
    edad                    NUMBER(3),
    -- Columna 18: Discapacidad
    disc_auditiva           CHAR(1) DEFAULT 'N' NOT NULL,
    disc_visual             CHAR(1) DEFAULT 'N' NOT NULL,
    disc_cognitiva          CHAR(1) DEFAULT 'N' NOT NULL,
    disc_mental             CHAR(1) DEFAULT 'N' NOT NULL,
    disc_fisica             CHAR(1) DEFAULT 'N' NOT NULL,
    -- Columna 19: Direccion de residencia
    direccion_residencia    VARCHAR2(200),
    -- Zona o barrio
    zona_barrio             VARCHAR2(100),
    -- Columna 20: Telefono
    telefono                VARCHAR2(20),
    -- Columna 21: Representado (Si/No)
    representado            CHAR(1) DEFAULT 'N' NOT NULL,
    -- Columnas 3-12: datos de la jornada / evento
    fecha_diligenciamiento  DATE,
    departamento            VARCHAR2(100),
    municipio               VARCHAR2(100),
    lugar_direccion         VARCHAR2(200),
    actividad_desarrollada  VARCHAR2(200),
    linea_estrategica       VARCHAR2(200),
    programa                VARCHAR2(200),
    proyecto                VARCHAR2(200),
    beneficios_entregados   VARCHAR2(200),
    poblacion_familias      CHAR(1) DEFAULT 'N' NOT NULL,
    poblacion_adulto_mayor  CHAR(1) DEFAULT 'N' NOT NULL,
    poblacion_ninez         CHAR(1) DEFAULT 'N' NOT NULL,
    poblacion_etnias        CHAR(1) DEFAULT 'N' NOT NULL,
    -- Auditoria
    creado_en               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    actualizado_en          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_beneficiarios_documento UNIQUE (documento_identidad),
    CONSTRAINT ck_beneficiarios_sexo CHECK (sexo IN ('F','M')),
    CONSTRAINT ck_beneficiarios_disc_aud CHECK (disc_auditiva IN ('S','N')),
    CONSTRAINT ck_beneficiarios_disc_vis CHECK (disc_visual IN ('S','N')),
    CONSTRAINT ck_beneficiarios_disc_cog CHECK (disc_cognitiva IN ('S','N')),
    CONSTRAINT ck_beneficiarios_disc_men CHECK (disc_mental IN ('S','N')),
    CONSTRAINT ck_beneficiarios_disc_fis CHECK (disc_fisica IN ('S','N')),
    CONSTRAINT ck_beneficiarios_repres CHECK (representado IN ('S','N')),
    CONSTRAINT ck_beneficiarios_pob_fam CHECK (poblacion_familias IN ('S','N')),
    CONSTRAINT ck_beneficiarios_pob_am  CHECK (poblacion_adulto_mayor IN ('S','N')),
    CONSTRAINT ck_beneficiarios_pob_nin CHECK (poblacion_ninez IN ('S','N')),
    CONSTRAINT ck_beneficiarios_pob_etn CHECK (poblacion_etnias IN ('S','N'))
);

CREATE INDEX ix_beneficiarios_nombres ON beneficiarios (nombres_apellidos);

-- Mantiene actualizado_en al dia en cada UPDATE
CREATE OR REPLACE TRIGGER trg_beneficiarios_upd
BEFORE UPDATE ON beneficiarios
FOR EACH ROW
BEGIN
    :NEW.actualizado_en := SYSTIMESTAMP;
END;
/

-- ---------------------------------------------------------------------
-- Tabla: usuarios_admin
-- Usuarios con acceso al panel administrativo.
-- ---------------------------------------------------------------------
CREATE TABLE usuarios_admin (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario           VARCHAR2(50)  NOT NULL,
    password_hash     VARCHAR2(200) NOT NULL,
    nombre_completo   VARCHAR2(200),
    activo            CHAR(1) DEFAULT 'S' NOT NULL,
    creado_en         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_usuarios_admin_usuario UNIQUE (usuario),
    CONSTRAINT ck_usuarios_admin_activo CHECK (activo IN ('S','N'))
);
