-- =====================================================================
-- FIMLM - Registro de Beneficiarios (Jornadas de Apoyo)
-- Esquema Postgres (Neon / cualquier Postgres 13+)
-- Equivalente a db/ddl/01_tables.sql + 02_ajustes.sql (version Oracle),
-- adaptado para el despliegue gratuito en Neon + Render.
-- =====================================================================

CREATE TABLE beneficiarios (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_identidad     VARCHAR(20)  NOT NULL,
    nombres_apellidos       VARCHAR(200) NOT NULL,
    sexo                    CHAR(1),
    edad                    SMALLINT,
    disc_auditiva           CHAR(1) NOT NULL DEFAULT 'N',
    disc_visual             CHAR(1) NOT NULL DEFAULT 'N',
    disc_cognitiva          CHAR(1) NOT NULL DEFAULT 'N',
    disc_mental             CHAR(1) NOT NULL DEFAULT 'N',
    disc_fisica             CHAR(1) NOT NULL DEFAULT 'N',
    direccion_residencia    VARCHAR(200),
    zona_barrio             VARCHAR(100),
    telefono                VARCHAR(20),
    representado            CHAR(1) NOT NULL DEFAULT 'N',
    es_externo              CHAR(1) NOT NULL DEFAULT 'N',
    registrado              CHAR(1) NOT NULL DEFAULT 'N',
    fecha_diligenciamiento  DATE,
    departamento            VARCHAR(100),
    municipio               VARCHAR(100),
    lugar_direccion         VARCHAR(200),
    actividad_desarrollada  VARCHAR(200),
    linea_estrategica       VARCHAR(200),
    programa                VARCHAR(200),
    proyecto                VARCHAR(200),
    beneficios_entregados   VARCHAR(200),
    poblacion_familias      CHAR(1) NOT NULL DEFAULT 'N',
    poblacion_adulto_mayor  CHAR(1) NOT NULL DEFAULT 'N',
    poblacion_ninez         CHAR(1) NOT NULL DEFAULT 'N',
    poblacion_etnias        CHAR(1) NOT NULL DEFAULT 'N',
    creado_en               TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en          TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_beneficiarios_documento UNIQUE (documento_identidad),
    CONSTRAINT ck_beneficiarios_sexo CHECK (sexo IN ('F','M')),
    CONSTRAINT ck_beneficiarios_disc_aud CHECK (disc_auditiva IN ('S','N')),
    CONSTRAINT ck_beneficiarios_disc_vis CHECK (disc_visual IN ('S','N')),
    CONSTRAINT ck_beneficiarios_disc_cog CHECK (disc_cognitiva IN ('S','N')),
    CONSTRAINT ck_beneficiarios_disc_men CHECK (disc_mental IN ('S','N')),
    CONSTRAINT ck_beneficiarios_disc_fis CHECK (disc_fisica IN ('S','N')),
    CONSTRAINT ck_beneficiarios_repres CHECK (representado IN ('S','N')),
    CONSTRAINT ck_beneficiarios_externo CHECK (es_externo IN ('S','N')),
    CONSTRAINT ck_beneficiarios_registrado CHECK (registrado IN ('S','N')),
    CONSTRAINT ck_beneficiarios_pob_fam CHECK (poblacion_familias IN ('S','N')),
    CONSTRAINT ck_beneficiarios_pob_am  CHECK (poblacion_adulto_mayor IN ('S','N')),
    CONSTRAINT ck_beneficiarios_pob_nin CHECK (poblacion_ninez IN ('S','N')),
    CONSTRAINT ck_beneficiarios_pob_etn CHECK (poblacion_etnias IN ('S','N'))
);

CREATE INDEX ix_beneficiarios_nombres ON beneficiarios (nombres_apellidos);
CREATE INDEX ix_beneficiarios_registrado ON beneficiarios (registrado);

CREATE OR REPLACE FUNCTION trg_set_actualizado_en() RETURNS TRIGGER AS $$
BEGIN
  NEW.actualizado_en := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER beneficiarios_actualizado_en
BEFORE UPDATE ON beneficiarios
FOR EACH ROW
EXECUTE FUNCTION trg_set_actualizado_en();

CREATE TABLE usuarios_admin (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario           VARCHAR(50)  NOT NULL,
    password_hash     VARCHAR(200) NOT NULL,
    nombre_completo   VARCHAR(200),
    activo            CHAR(1) NOT NULL DEFAULT 'S',
    creado_en         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_usuarios_admin_usuario UNIQUE (usuario),
    CONSTRAINT ck_usuarios_admin_activo CHECK (activo IN ('S','N'))
);

CREATE TABLE configuracion (
    id              SMALLINT PRIMARY KEY DEFAULT 1,
    max_registros   INTEGER NOT NULL DEFAULT 150,
    pct_externos    INTEGER NOT NULL DEFAULT 30,
    actualizado_en  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_configuracion_id CHECK (id = 1),
    CONSTRAINT ck_configuracion_max CHECK (max_registros > 0),
    CONSTRAINT ck_configuracion_pct CHECK (pct_externos BETWEEN 0 AND 100)
);

INSERT INTO configuracion (id, max_registros, pct_externos) VALUES (1, 150, 30);
